export const queryKeys = {
  accounts: ['accounts'] as const,
  account: (accountId: string) => ['accounts', accountId] as const,
  me: ['me'] as const,
  settings: ['settings'] as const,
  strategies: ['strategies'] as const,
  strategyList: ['strategies', 'list'] as const,
  strategyListFiltered: (filters: Record<string, string | number | boolean | undefined>) => ['strategies', 'list', filters] as const,
  strategyDetail: (id: string) => ['strategies', 'detail', id] as const,
  paperEvaluationScopes: (accountId: string) => ['accounts', accountId, 'evidence-scopes'] as const,
  strategyReportLatest: (accountId: string, evidenceScopeId: string, id: string, reportType: string) => ['accounts', accountId, 'evidence-scopes', evidenceScopeId, 'strategies', id, 'reports', 'latest', reportType] as const,
  strategyReports: (accountId: string, evidenceScopeId: string, id: string, filters: Record<string, string | number | undefined>) => ['accounts', accountId, 'evidence-scopes', evidenceScopeId, 'strategies', id, 'reports', filters] as const,
  riskStatus: (accountId: string) => ['accounts', accountId, 'risk', 'status'] as const,
  riskCockpit: (accountId: string) => ['accounts', accountId, 'risk', 'cockpit'] as const,
  riskBreakers: ['risk', 'breakers'] as const,
  portfolioSummary: (accountId: string) => ['accounts', accountId, 'portfolio', 'summary'] as const,
  portfolioPositions: (accountId: string, filters: Record<string, string | number | undefined>) => ['accounts', accountId, 'portfolio', 'positions', filters] as const,
  portfolioOpenPositions: (accountId: string, filters: Record<string, string | number | undefined>) => ['accounts', accountId, 'portfolio', 'positions', 'open', filters] as const,
  allocatorDiagnostics: (accountId: string) => ['accounts', accountId, 'portfolio', 'allocator', 'diagnostics'] as const,
  allocatorSummary: (accountId: string) => ['accounts', accountId, 'portfolio', 'allocator', 'summary'] as const,
  allocatorOpportunities: (accountId: string, filters: Record<string, string | number | undefined>) => ['accounts', accountId, 'portfolio', 'allocator', 'opportunities', filters] as const,
  allocatorDecisions: (accountId: string, filters: Record<string, string | number | undefined>) => ['accounts', accountId, 'portfolio', 'allocator', 'decisions', filters] as const,
  runningRuns: (accountId: string) => ['accounts', accountId, 'runs', 'list', { status: 'running' }] as const,
  runsListFiltered: (accountId: string, filters: Record<string, string | number | undefined>) => ['accounts', accountId, 'runs', 'list', filters] as const,
  runDetail: (accountId: string, id: string, tradeDate: string) => ['accounts', accountId, 'runs', id, tradeDate] as const,
  runDecisions: (accountId: string, id: string, tradeDate: string, filters: Record<string, string | number | boolean | undefined>) => ['accounts', accountId, 'runs', id, tradeDate, 'decisions', filters] as const,
  runSnapshot: (accountId: string, id: string, tradeDate: string) => ['accounts', accountId, 'runs', id, tradeDate, 'snapshot'] as const,
  eventsListFiltered: (accountId: string, filters: Record<string, string | number | undefined>) => ['accounts', accountId, 'events', 'list', filters] as const,
  ordersListFiltered: (accountId: string, filters: Record<string, string | number | undefined>) => ['accounts', accountId, 'orders', 'list', filters] as const,
  orderDetail: (accountId: string, id: string) => ['accounts', accountId, 'orders', 'detail', id] as const,
  tradesListFiltered: (accountId: string, filters: Record<string, string | number | undefined>) => ['accounts', accountId, 'trades', 'list', filters] as const,
  strategyRuns: (accountId: string, strategyId: string) => ['accounts', accountId, 'runs', 'list', { strategyId }] as const,
  automationHealth: ['automation', 'health'] as const,
  automationStatus: ['automation', 'status'] as const,
  automationRuns: (filters: Record<string, string | number | undefined>) => ['automation', 'runs', filters] as const,
  automationDetail: (name: string) => ['automation', 'detail', name] as const,
  health: ['health'] as const,
  releaseReadiness: ['release', 'readiness'] as const,
  cutoverStatus: ['release', 'cutover-status'] as const,
  economicAccounts: (accountId: string) => ['accounts', accountId, 'economic', 'accounts'] as const,
  economicAccount: (accountId: string, id: string) => ['accounts', accountId, 'economic', 'accounts', id] as const,
  economicCapitalSummary: (accountId: string, id: string) => ['accounts', accountId, 'economic', 'accounts', id, 'capital-summary'] as const,
  economicCapitalFlows: (accountId: string, id: string) => ['accounts', accountId, 'economic', 'accounts', id, 'capital-flows'] as const,
  economicLedgerTransaction: (accountId: string, id: string) => ['accounts', accountId, 'economic', 'ledger-transactions', id] as const,
  milestoneAssessment: (id: string) => ['evidence', 'assessments', id] as const,
  copyLeaders: (accountId: string) => ['accounts', accountId, 'copy-trading', 'leaders'] as const,
  copyLeader: (accountId: string, id: string) => ['accounts', accountId, 'copy-trading', 'leaders', id] as const,
  copySubscriptions: (accountId: string) => ['accounts', accountId, 'copy-trading', 'subscriptions'] as const,
  copySubscription: (accountId: string, id: string) => ['accounts', accountId, 'copy-trading', 'subscriptions', id] as const,
  copyIntents: (accountId: string, id: string) => ['accounts', accountId, 'copy-trading', 'subscriptions', id, 'intents'] as const,
}
