export const queryKeys = {
  me: ['me'] as const,
  settings: ['settings'] as const,
  strategies: ['strategies'] as const,
  strategyList: ['strategies', 'list'] as const,
  strategyListFiltered: (filters: Record<string, string | number | boolean | undefined>) => ['strategies', 'list', filters] as const,
  strategyDetail: (id: string) => ['strategies', 'detail', id] as const,
  strategyReportLatest: (id: string, reportType: string) => ['strategies', 'detail', id, 'reports', 'latest', reportType] as const,
  strategyReports: (id: string, filters: Record<string, string | number | undefined>) => ['strategies', 'detail', id, 'reports', 'list', filters] as const,
  riskStatus: ['risk', 'status'] as const,
  riskCockpit: ['risk', 'cockpit'] as const,
  riskBreakers: ['risk', 'breakers'] as const,
  portfolioSummary: ['portfolio', 'summary'] as const,
  portfolioPositions: (filters: Record<string, string | number | undefined>) => ['portfolio', 'positions', filters] as const,
  portfolioOpenPositions: (filters: Record<string, string | number | undefined>) => ['portfolio', 'positions', 'open', filters] as const,
  allocatorDiagnostics: ['portfolio', 'allocator', 'diagnostics'] as const,
  allocatorSummary: ['portfolio', 'allocator', 'summary'] as const,
  allocatorOpportunities: (filters: Record<string, string | number | undefined>) => ['portfolio', 'allocator', 'opportunities', filters] as const,
  allocatorDecisions: (filters: Record<string, string | number | undefined>) => ['portfolio', 'allocator', 'decisions', filters] as const,
  runningRuns: ['runs', 'list', { status: 'running' }] as const,
  runsListFiltered: (filters: Record<string, string | number | undefined>) => ['runs', 'list', filters] as const,
  runDetail: (id: string) => ['runs', 'detail', id] as const,
  runDecisions: (id: string, filters: Record<string, string | number | boolean | undefined>) => ['runs', 'detail', id, 'decisions', filters] as const,
  runSnapshot: (id: string) => ['runs', 'detail', id, 'snapshot'] as const,
  eventsListFiltered: (filters: Record<string, string | number | undefined>) => ['events', 'list', filters] as const,
  ordersListFiltered: (filters: Record<string, string | number | undefined>) => ['orders', 'list', filters] as const,
  orderDetail: (id: string) => ['orders', 'detail', id] as const,
  tradesListFiltered: (filters: Record<string, string | number | undefined>) => ['trades', 'list', filters] as const,
  strategyRuns: (strategyId: string) => ['runs', 'list', { strategyId }] as const,
  automationHealth: ['automation', 'health'] as const,
  automationStatus: ['automation', 'status'] as const,
  automationRuns: (filters: Record<string, string | number | undefined>) => ['automation', 'runs', filters] as const,
  automationDetail: (name: string) => ['automation', 'detail', name] as const,
  health: ['health'] as const,
  releaseReadiness: ['release', 'readiness'] as const,
  cutoverStatus: ['release', 'cutover-status'] as const,
  economicAccounts: ['economic', 'accounts'] as const,
  economicAccount: (id: string) => ['economic', 'accounts', id] as const,
  economicCapitalSummary: (id: string) => ['economic', 'accounts', id, 'capital-summary'] as const,
  economicCapitalFlows: (id: string) => ['economic', 'accounts', id, 'capital-flows'] as const,
  economicLedgerTransaction: (id: string) => ['economic', 'ledger-transactions', id] as const,
  milestoneAssessment: (id: string) => ['evidence', 'assessments', id] as const,
  copyLeaders: ['copy-trading', 'leaders'] as const,
  copyLeader: (id: string) => ['copy-trading', 'leaders', id] as const,
  copySubscriptions: ['copy-trading', 'subscriptions'] as const,
  copySubscription: (id: string) => ['copy-trading', 'subscriptions', id] as const,
  copyIntents: (id: string) => ['copy-trading', 'subscriptions', id, 'intents'] as const,
}
